merged

diff --git a/app/install/setup/all/bin/app-update b/app/install/setup/all/bin/app-update
--- a/app/install/setup/all/bin/app-update
+++ b/app/install/setup/all/bin/app-update
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+lib ./install/git.sh
+
 constant ./install
 
 cfg install
@@ -8,6 +10,11 @@ _app_update_update_all() {
   for _APP_NAME in "$@"; do
     app-install $_APP_NAME || log_warn "$_APP_NAME - installation failed"
   done
+}
+
+_git_has_updates || {
+  log_warn "no updates detected, aborting"
+  exit
 }
 
 if [ $# -eq 0 ]; then
